import type { Category, Product, Testimonial } from '@/lib/types'

export const categories: Category[] = [
  {
    id: 'c1',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'Cpu',
    description: 'Smart devices, audio & wearables',
    productCount: 42,
  },
  {
    id: 'c2',
    name: 'Fashion',
    slug: 'fashion',
    icon: 'Shirt',
    description: 'Apparel, footwear & outerwear',
    productCount: 68,
  },
  {
    id: 'c3',
    name: 'Home',
    slug: 'home',
    icon: 'Lamp',
    description: 'Decor, lighting & essentials',
    productCount: 35,
  },
  {
    id: 'c4',
    name: 'Grocery',
    slug: 'grocery',
    icon: 'ShoppingBasket',
    description: 'Organic & everyday staples',
    productCount: 120,
  },
  {
    id: 'c5',
    name: 'Accessories',
    slug: 'accessories',
    icon: 'Watch',
    description: 'Bags, watches & extras',
    productCount: 54,
  },
  {
    id: 'c6',
    name: 'Beauty',
    slug: 'beauty',
    icon: 'Sparkles',
    description: 'Skincare & wellness',
    productCount: 47,
  },
]

const sharedReviews = [
  {
    id: 'r1',
    author: 'Amelia R.',
    avatar: '/images/avatars/avatar-1.png',
    rating: 5,
    date: 'March 2, 2026',
    title: 'Exceeded my expectations',
    body: 'The build quality is fantastic and it arrived earlier than expected. Absolutely worth every penny.',
  },
  {
    id: 'r2',
    author: 'Daniel K.',
    avatar: '/images/avatars/avatar-2.png',
    rating: 4,
    date: 'February 18, 2026',
    title: 'Great value',
    body: 'Works exactly as described. Packaging was premium and the product feels durable.',
  },
  {
    id: 'r3',
    author: 'Priya S.',
    avatar: '/images/avatars/avatar-3.png',
    rating: 5,
    date: 'February 5, 2026',
    title: 'Highly recommend',
    body: 'One of my best online purchases this year. The customer service was also very responsive.',
  },
]

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Aurora Wireless Headphones',
    slug: 'aurora-wireless-headphones',
    category: 'Electronics',
    categorySlug: 'electronics',
    price: 189,
    originalPrice: 249,
    rating: 4.8,
    reviewCount: 214,
    image: '/images/products/headphones.png',
    gallery: ['/images/products/headphones.png'],
    inStock: true,
    stockCount: 32,
    badge: '24% OFF',
    shortDescription:
      'Immersive active noise cancelling headphones with 40-hour battery life.',
    description:
      'The Aurora headphones deliver studio-grade sound with adaptive active noise cancellation. Plush memory-foam ear cushions and a lightweight frame make them comfortable for all-day listening, while the 40-hour battery keeps you going for days.',
    specifications: [
      { label: 'Driver', value: '40mm dynamic' },
      { label: 'Battery', value: '40 hours' },
      { label: 'Connectivity', value: 'Bluetooth 5.3' },
      { label: 'Weight', value: '245g' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p2',
    name: 'Pulse Smart Watch',
    slug: 'pulse-smart-watch',
    category: 'Electronics',
    categorySlug: 'electronics',
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviewCount: 176,
    image: '/images/products/smartwatch.png',
    gallery: ['/images/products/smartwatch.png'],
    inStock: true,
    stockCount: 18,
    badge: 'Best Seller',
    shortDescription:
      'Track fitness, sleep and heart rate with a vivid always-on display.',
    description:
      'The Pulse Smart Watch keeps you connected and healthy with 24/7 heart-rate monitoring, sleep tracking, and over 100 workout modes. Its bright always-on AMOLED display is protected by scratch-resistant glass and rated for swimming.',
    specifications: [
      { label: 'Display', value: '1.4" AMOLED' },
      { label: 'Battery', value: '7 days' },
      { label: 'Water rating', value: '5 ATM' },
      { label: 'Sensors', value: 'HR, SpO2, GPS' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p3',
    name: 'Heritage Leather Jacket',
    slug: 'heritage-leather-jacket',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 320,
    rating: 4.9,
    reviewCount: 89,
    image: '/images/products/jacket.png',
    gallery: ['/images/products/jacket.png'],
    inStock: true,
    stockCount: 12,
    badge: 'New',
    shortDescription:
      'Hand-finished full-grain leather jacket built to last a lifetime.',
    description:
      'Crafted from premium full-grain leather, the Heritage jacket ages beautifully with every wear. Tailored for a modern fit with a quilted interior lining and antique-brass hardware.',
    specifications: [
      { label: 'Material', value: 'Full-grain leather' },
      { label: 'Lining', value: 'Quilted viscose' },
      { label: 'Fit', value: 'Modern tailored' },
      { label: 'Care', value: 'Professional clean' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p4',
    name: 'Trailblazer Running Sneakers',
    slug: 'trailblazer-running-sneakers',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviewCount: 143,
    image: '/images/products/sneakers.png',
    gallery: ['/images/products/sneakers.png'],
    inStock: true,
    stockCount: 44,
    badge: '19% OFF',
    shortDescription:
      'Responsive cushioning and breathable knit for everyday runs.',
    description:
      'Engineered for comfort and speed, the Trailblazer features a responsive foam midsole and a breathable knit upper that moves with you. A durable rubber outsole grips every surface.',
    specifications: [
      { label: 'Upper', value: 'Engineered knit' },
      { label: 'Midsole', value: 'Responsive foam' },
      { label: 'Drop', value: '8mm' },
      { label: 'Weight', value: '260g' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p5',
    name: 'Lumen Ceramic Table Lamp',
    slug: 'lumen-ceramic-table-lamp',
    category: 'Home',
    categorySlug: 'home',
    price: 89,
    rating: 4.7,
    reviewCount: 61,
    image: '/images/products/lamp.png',
    gallery: ['/images/products/lamp.png'],
    inStock: true,
    stockCount: 27,
    shortDescription:
      'Warm ambient lighting with a handcrafted ceramic base and linen shade.',
    description:
      'The Lumen lamp brings a soft, warm glow to any space. Its handcrafted ceramic base pairs with a natural linen shade for understated elegance that suits any room.',
    specifications: [
      { label: 'Base', value: 'Handcrafted ceramic' },
      { label: 'Shade', value: 'Natural linen' },
      { label: 'Bulb', value: 'E27 (not included)' },
      { label: 'Height', value: '48cm' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p6',
    name: 'Highland Organic Coffee',
    slug: 'highland-organic-coffee',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 24,
    originalPrice: 29,
    rating: 4.8,
    reviewCount: 302,
    image: '/images/products/coffee.png',
    gallery: ['/images/products/coffee.png'],
    inStock: true,
    stockCount: 88,
    badge: 'Organic',
    shortDescription:
      'Single-origin, medium-roast beans with notes of cocoa and citrus.',
    description:
      'Sourced from highland farms and roasted in small batches, Highland coffee delivers a smooth, balanced cup with notes of cocoa and bright citrus. Certified organic and fair trade.',
    specifications: [
      { label: 'Roast', value: 'Medium' },
      { label: 'Origin', value: 'Single-origin' },
      { label: 'Weight', value: '500g' },
      { label: 'Certification', value: 'Organic, Fair Trade' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p7',
    name: 'Voyager Leather Backpack',
    slug: 'voyager-leather-backpack',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 179,
    originalPrice: 219,
    rating: 4.7,
    reviewCount: 97,
    image: '/images/products/backpack.png',
    gallery: ['/images/products/backpack.png'],
    inStock: true,
    stockCount: 21,
    badge: '18% OFF',
    shortDescription:
      'Water-resistant leather backpack with a padded laptop sleeve.',
    description:
      'The Voyager backpack combines rugged water-resistant leather with a thoughtful interior layout, including a padded 16" laptop sleeve and multiple organizer pockets for travel and work.',
    specifications: [
      { label: 'Material', value: 'Water-resistant leather' },
      { label: 'Capacity', value: '22L' },
      { label: 'Laptop', value: 'Up to 16"' },
      { label: 'Pockets', value: '6 total' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p8',
    name: 'Botanica Radiance Serum',
    slug: 'botanica-radiance-serum',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 46,
    rating: 4.9,
    reviewCount: 258,
    image: '/images/products/serum.png',
    gallery: ['/images/products/serum.png'],
    inStock: false,
    stockCount: 0,
    badge: 'Sold Out',
    shortDescription:
      'Vitamin-C brightening serum for a smooth, radiant complexion.',
    description:
      'Botanica Radiance Serum blends stabilized vitamin C with hyaluronic acid and botanical extracts to brighten, hydrate and smooth skin. Lightweight, fast-absorbing and suitable for all skin types.',
    specifications: [
      { label: 'Key active', value: '15% Vitamin C' },
      { label: 'Volume', value: '30ml' },
      { label: 'Skin type', value: 'All types' },
      { label: 'Cruelty-free', value: 'Yes' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sophia Bennett',
    role: 'Verified Buyer',
    avatar: '/images/avatars/avatar-1.png',
    rating: 5,
    quote:
      'Verdant has completely changed how I shop online. Fast delivery, premium packaging, and products that actually match the photos.',
  },
  {
    id: 't2',
    name: 'Marcus Lee',
    role: 'Verified Buyer',
    avatar: '/images/avatars/avatar-2.png',
    rating: 5,
    quote:
      'The checkout is effortless and the quality is outstanding. I have recommended Verdant to my whole family.',
  },
  {
    id: 't3',
    name: 'Ana Duarte',
    role: 'Verified Buyer',
    avatar: '/images/avatars/avatar-3.png',
    rating: 4,
    quote:
      'Beautiful store experience and thoughtful customer support. My orders always arrive on time and well protected.',
  },
]
