import type { Category, Product, Testimonial } from '@/lib/types'

export const categories: Category[] = [
  {
    id: 'c1',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'Cpu',
    description: 'Smart devices, audio & wearables',
    productCount: 42,
  },
  {
    id: 'c2',
    name: 'Fashion',
    slug: 'fashion',
    icon: 'Shirt',
    description: 'Apparel, footwear & outerwear',
    productCount: 68,
  },
  {
    id: 'c3',
    name: 'Home',
    slug: 'home',
    icon: 'Lamp',
    description: 'Decor, lighting & essentials',
    productCount: 35,
  },
  {
    id: 'c4',
    name: 'Grocery',
    slug: 'grocery',
    icon: 'ShoppingBasket',
    description: 'Organic & everyday staples',
    productCount: 120,
  },
  {
    id: 'c5',
    name: 'Accessories',
    slug: 'accessories',
    icon: 'Watch',
    description: 'Bags, watches & extras',
    productCount: 54,
  },
  {
    id: 'c6',
    name: 'Beauty',
    slug: 'beauty',
    icon: 'Sparkles',
    description: 'Skincare & wellness',
    productCount: 47,
  },
]

const sharedReviews = [
  {
    id: 'r1',
    author: 'Sandra Lee',
    avatar: '/images/avatars/avatar-1.png',
    rating: 5,
    date: 'June 2, 2026',
    title: 'Exceeded my expectations',
    body: 'The build quality is fantastic and it arrived earlier than expected. Absolutely worth every penny.',
  },
  {
    id: 'r2',
    author: 'Salim AP',
    avatar: '/images/avatars/avatar-2.png',
    rating: 4,
    date: 'July 18, 2026',
    title: 'Great value',
    body: 'Works exactly as described. Packaging was premium and the product feels durable.',
  },
  {
    id: 'r3',
    author: 'Hiba KP',
    avatar: '/images/avatars/avatar-3.png',
    rating: 5,
    date: 'August 5, 2026',
    title: 'Highly recommend',
    body: 'One of my best online purchases this year. The customer service was also very responsive.',
  },
]

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Cup Holder Tissue',
    slug: 'cup-holder-tissue-green',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 140,
    originalPrice: 149,
    rating: 4.8,
    reviewCount: 214,
    image: '/images/products/green_tissue.png',
    gallery: ['/images/products/green_tissue.png'],
    inStock: true,
    stockCount: 32,
    badge: 'Green',
    shortDescription:
      'Compact, eco-friendly green tissue cylinder designed to fit perfectly in your car cup holder.',
    description:
      'Keep your vehicle clean and stylish with our Premium Cup Holder Tissue (Green edition). Specially designed to fit standard car cup holders, offering ultra-soft, absorbent 3-ply tissues with easy pull-out access while driving.',
    specifications: [
      { label: 'Material', value: '100% Virgin Wood Pulp' },
      { label: 'Capacity', value: '60 Tissues (3-ply)' },
      { label: 'Fit', value: 'Standard Car Cup Holder' },
      { label: 'Color', value: 'Green' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p2',
    name: 'Cup Holder Tissue',
    slug: 'cup-holder-tissue-blue',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 140,
    originalPrice: 149,
    rating: 4.2,
    reviewCount: 176,
    image: '/images/products/Blue_tissue.png',
    gallery: ['/images/products/Blue_tissue.png'],
    inStock: true,
    stockCount: 18,
    badge: 'Blue',
    shortDescription:
      'Sleek blue tissue cylinder tailored to fit car cup holders for convenient accessibility.',
    description:
      'Upgrade your driving convenience with our Premium Cup Holder Tissue (Blue edition). Fits snugly into standard cup holders, offering durable, absorbent, and gentle tissues for quick cleanups and everyday spills.',
    specifications: [
      { label: 'Material', value: '100% Virgin Wood Pulp' },
      { label: 'Capacity', value: '60 Tissues (3-ply)' },
      { label: 'Fit', value: 'Standard Car Cup Holder' },
      { label: 'Color', value: 'Blue' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p3',
    name: 'Air freshener Spray',
    slug: 'air-freshener-spray',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 299,
    rating: 4.9,
    reviewCount: 89,
    image: '/images/products/perfume.png',
    gallery: ['/images/products/perfume.png'],
    inStock: true,
    stockCount: 12,
    badge: 'New',
    shortDescription:
      'Long-lasting luxury car air freshener spray for an instant fresh ambiance.',
    description:
      'Transform your vehicle or living space with our premium Air Freshener Spray. Formulated with natural essential oils to eliminate tough odors instantly and diffuse a refreshing, invigorating fragrance.',
    specifications: [
      { label: 'Volume', value: '150ml' },
      { label: 'Fragrance', value: 'Fresh Citrus & Linen' },
      { label: 'Scent Duration', value: 'Up to 48 hours per spray' },
      { label: 'Formula', value: 'Non-toxic, Eco-friendly' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p4',
    name: 'Papper Air freshener',
    slug: 'papper-air-freshener',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 30,
    originalPrice: 50,
    rating: 4.5,
    reviewCount: 143,
    image: '/images/products/paper.png',
    gallery: ['/images/products/paper.png'],
    inStock: true,
    stockCount: 44,
    badge: '19% OFF',
    shortDescription:
      'Hanging paper air freshener infused with rich fragrant oils for cars and compact spaces.',
    description:
      'Infuse your car, closet, or room with a pleasant scent using our Paper Air Freshener. Easy to hang on your rearview mirror, providing a steady release of fresh aroma over several weeks.',
    specifications: [
      { label: 'Material', value: 'High-absorbency Scented Paperboard' },
      { label: 'Lifespan', value: 'Up to 30 Days' },
      { label: 'Mounting', value: 'Hanging Cord Included' },
      { label: 'Fragrance', value: 'Ocean Breeze' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p5',
    name: 'Car Holder Tissue Combo',
    slug: 'car-holder-tissue-combo',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 389,
    rating: 4.7,
    reviewCount: 61,
    image: '/images/products/combo.png',
    gallery: ['/images/products/combo.png'],
    inStock: true,
    stockCount: 27,
    shortDescription:
      'Value combo pack of cup holder tissues and car essential accessories.',
    description:
      'The ultimate car cleanliness bundle! Our Car Holder Tissue Combo includes multiple tissue cylinders along with essential car care items to keep your interior neat, tidy, and smelling fresh.',
    specifications: [
      { label: 'Package Includes', value: '2x Tissue Canisters + Spray' },
      { label: 'Total Tissues', value: '120 Sheets (3-ply)' },
      { label: 'Compatibility', value: 'Universal Car Interior' },
      { label: 'Value', value: 'Combo Savings Pack' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p6',
    name: 'Travel Kit Essentials',
    slug: 'travel-kit-essentials',
    category: 'travel',
    categorySlug: 'travel',
    price: 199,
    originalPrice: 249,
    rating: 4.8,
    reviewCount: 302,
    image: '/images/products/traval_kit.png',
    gallery: ['/images/products/traval_kit.png'],
    inStock: true,
    stockCount: 88,
    badge: 'Organic',
    shortDescription:
      'Complete travel kit packed with essential toiletries and car travel organizers.',
    description:
      'Stay prepared wherever your journey takes you with the Travel Kit Essentials. Featuring a durable, water-resistant pouch packed with compact personal care items, wet wipes, and travel essentials.',
    specifications: [
      { label: 'Items Included', value: '8 Travel Essentials' },
      { label: 'Case Material', value: 'Waterproof Canvas Pouch' },
      { label: 'Dimensions', value: '25cm x 15cm x 10cm' },
      { label: 'TSA Approved', value: 'Yes' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p7',
    name: 'Female Travel Kit',
    slug: 'female-travel-kit',
    category: 'travel',
    categorySlug: 'travel',
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviewCount: 97,
    image: '/images/products/Capture.png',
    gallery: ['/images/products/Capture.png'],
    inStock: true,
    stockCount: 21,
    badge: 'Female',
    shortDescription:
      'Curated female travel kit featuring hygiene, skincare, and travel convenience items.',
    description:
      'Tailored for women on the move, the Female Travel Kit includes hygiene essentials, soft tissues, skincare mini-items, and compact organizers in an elegant travel pouch.',
    specifications: [
      { label: 'Items Included', value: '10 Personal Care Items' },
      { label: 'Pouch Finish', value: 'Rose Gold / Premium Leatherette' },
      { label: 'Dimensions', value: '22cm x 14cm x 8cm' },
      { label: 'Suitability', value: 'Flight & Road Trip Ready' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
  {
    id: 'p8',
    name: 'Car Shampoo',
    slug: 'car-shampoo',
    category: 'Automotive',
    categorySlug: 'automotive',
    price: 119.99,
    rating: 4.5,
    reviewCount: 120,
    image: '/images/products/shamboo.png',
    gallery: ['/images/products/shamboo.png'],
    inStock: false,
    stockCount: 10,
    badge: 'New',
    shortDescription:
      'High-foaming, pH-balanced car wash shampoo for a brilliant streak-free shine.',
    description:
      'Restore your vehicle’s factory shine with our high-foaming Car Shampoo. Safely strips away stubborn dirt, grime, and mud without removing existing wax coatings or damaging clear coats.',
    specifications: [
      { label: 'Volume', value: '500ml' },
      { label: 'Formula', value: 'pH-Balanced & Wax Safe' },
      { label: 'Dilution Ratio', value: '1:200 with Water' },
      { label: 'Finish', value: 'High Gloss Streak-Free' },
    ],
    reviews: sharedReviews,
    featured: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sandra Lee',
    role: 'Customer',
    avatar: '/images/avatars/avatar-1.png',
    rating: 5,
    quote:
      'Verdant has completely changed how I shop online. Fast delivery, premium packaging, and products that actually match the photos.',
  },
  {
    id: 't2',
    name: 'Salim AP',
    role: 'Customer',
    avatar: '/images/avatars/avatar-2.png',
    rating: 5,
    quote:
      'The checkout is effortless and the quality is outstanding. I have recommended Verdant to my whole family.',
  },
  {
    id: 't3',
    name: 'Hiba KP',
    role: 'Customer',
    avatar: '/images/avatars/avatar-3.png',
    rating: 4,
    quote:
      'Beautiful store experience and thoughtful customer support. My orders always arrive on time and well protected.',
  },
]
